name: SoundMuseum # The name of the App
include:
 - Projects/DndUI/project.yml
 - Projects/templates.yml
options: # Some general settings for the projectproject.yml
  minimumXcodeGenVersion: 2.14.0
  createIntermediateGroups: true # If the folders are nested, also nest the groups in Xcode
  indentWidth: 2 # indent by 2 spaces
  tabWidth: 2 # a tab is 2 spaces
  bundleIdPrefix: "kr.co.dnd"
configs:
  Debug: debug
  Release: release
targets:
  SoundMuseum:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: kr.co.dnd
      INFOPLIST_FILE: Projects/SoundMuseum/Supporting Files/Info.plist
    sources:
      - path: Sources
      - path: Resources
      - path: Supporting Files
        excludes:
          - Info.plist
    sources:  
      - path: Projects/SoundMuseum
    scheme: 
      testTargets:
        - SoundMuseumTests
      gatherCoverageData: true
    settings:
      OTHER_LDFLAGS: $(inherited) -all_load
    dependencies:
      - target: DndUI
    preBuildScripts:
      - name: SwiftLint
        script: |
                ${PODS_ROOT}/SwiftLint/swiftlint --config .swiftlint.yml
  SoundMuseumTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "13.0"
    settings:
      INFOPLIST_FILE: Projects/SoundMuseumTests/Info.plist
    sources:
      - path: Projects/SoundMuseumTests/Sources
    dependencies:
      - target: SoundMuseum
    scheme: 
      testTargets:
        - SoundMuseum
        - SoundMuseumTests
      gatherCoverageData: true