targets:
  {{cookiecutter.name}}:
    templates: [Framework]

  {{cookiecutter.name}}Tests:
    templates: [UnitTest]
    templateAttributes:
      testTarget: {{cookiecutter.name}}
    dependencies:
      - target: StyleShareTest

schemes:
  AllTests:
    build:
      targets:
        {{cookiecutter.name}}: test
    test:
      targets:
        - {{cookiecutter.name}}Tests
