targets:
  DndUI:
    templates: [Framework]
    settings:
      DEFINES_MODULE: YES
    deploymentTarget: "13.0"
    
  DndUITests:
    templates: [UnitTest]
    templateAttributes:
      testTarget: DndUI
    dependencies:
      - sdk: UIKit.framework
      - target: SoundMuseumTests

schemes:
  AllTests:
    build:
      targets:
        DndUI: test
    test:
      targets:
        - DndUITests